services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
