version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Build Docker containers
          command: docker-compose build
      - run:
          name: Run tests
          command: docker-compose run backend python test_app.py
